// projects/nx-workspace/apps/ui/personal-website-react/src/app/components/global/loading-spinner.tsx
type Props = {
  header?: string;
  message?: string;
};

export function LoadingSpinner({ header, message }: Props) {
  return (
    <div>
      <div className="flex items-center justify-center">
        <div className="animate-spin rounded-full h-20 w-20 border-t-2 border-b-2 border-blue-500" />
      </div>
      {header ? (
        <h2 className="mt-4 text-lg font-semibold text-gray-700 dark:text-gray-200 text-center">
          {header}
        </h2>
      ) : null}
      {message ? <p className="text-center mb-4">{message}</p> : null}
    </div>
  );
}

// projects/personal-website/frontend/src/app/components/global/loading-spinner/loading-spinner.component.ts
import { Component, Input } from '@angular/core';

@Component({
  standalone: true,
  selector: 'app-loading-spinner',
  templateUrl: './loading-spinner.component.html',
})
export class LoadingSpinnerComponent {
  @Input() header!: string;
  @Input() message!: string;
}

<div class="flex items-center justify-center">
  <div
    class="animate-spin rounded-full h-20 w-20 border-t-2 border-b-2 border-blue-500"
  ></div>
</div>
<h2 class="mt-4 text-lg font-semibold text-gray-700 text-center">
  {{ header }}
</h2>
<p class="text-center mb-4">
  {{ message }}
</p>
