// projects/demo-apps/react-demo/src/pages/Todo/TodoForm.tsx
import React from 'react';
import { useState } from 'react';
import { useTodos } from './TodoContext';

export default function TodoForm() {
  const { addTodo } = useTodos();
  const [inputValue, setInputValue] = useState('');

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (inputValue.trim()) {
      addTodo(inputValue);
      setInputValue('');
    }
  };

  return (
    <form onSubmit={handleSubmit}>
      <div className="input-group mb-3">
        <span className="input-group-text">Todo</span>
        <input
          type="text"
          value={inputValue}
          onChange={e => setInputValue(e.target.value)}
          className="form-control"
          placeholder="Add new todo"
        />
        <button className="btn btn-outline-secondary" type="submit">
          Button
        </button>
      </div>
    </form>
  );
}

// projects/demo-apps/vue-demo/src/components/forms/TodoForm.vue
<template>
<form @submit.prevent="handleSubmit">
      <div class="input-group mb-3">
        <span class="input-group-text" @click="handleSubmit">
          Todo
        </span>
        <input
          type="text"
          v-model="todo"
          class="form-control"
          placeholder="Add new todo"
        />
        <button class="btn btn-outline-secondary" type="submit">
          Add Todo
        </button>
      </div>
    </form>
</template>

<script setup lang="ts">
const todo = ''
const handleSubmit = () => {}
</script>
