// projects/nx-workspace/apps/ui/cloud-8-skate-angular/src/app/components/features/calendar-section/calendar-section.component.ts
import { isPlatformBrowser } from '@angular/common';
import { Component, HostListener, PLATFORM_ID, inject } from '@angular/core';
import { DomSanitizer, SafeResourceUrl } from '@angular/platform-browser';

@Component({
  selector: 'app-calendar-section',
  templateUrl: './calendar-section.component.html',
  imports: [],
})
export class CalendarSectionComponent {
  iframeSrc: SafeResourceUrl = '';

  private sanitizer = inject(DomSanitizer);
  private platformId = inject(PLATFORM_ID);

  constructor() {
    const width = isPlatformBrowser(this.platformId) ? window.innerWidth : 1024;
    this.updateIframeMode(width);
  }

  @HostListener('window:resize', ['$event'])
  onResize(event: Event) {
    this.updateIframeMode((event.target as Window).innerWidth);
  }

  private updateIframeMode(width: number) {
    const baseUrl = 'https://calendar.google.com/calendar/embed';
    const params = new URLSearchParams({
      wkst: '1',
      ctz: 'America/Toronto',
      title: 'Cloud8 Skate Events',
      src: 'ZmU3OTU0MzJjMDlhYzNmMmE5ZDc4MDdkZGY1NjhkZGE3ZmZkY2I1YzNlZDdkZDA3OGNhNmE2OTNhNjVjNzdiN0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t',
      mode: width < 768 ? 'AGENDA' : 'MONTH',
    });

    this.iframeSrc = this.sanitizer.bypassSecurityTrustResourceUrl(
      `${baseUrl}?${params.toString()}`,
    );
  }
}

<div
  class="lg:rounded-2xl lg:bg-white/70 lg:backdrop-blur-md lg:shadow-lg lg:p-10"
>
  <section class="mb-6 reveal-up hidden lg:block">
    <h2 class="mb-3 text-3xl font-bold lg:text-4xl">Calendar</h2>
    <p class="text-base leading-7 text-gray-700">
      Upcoming Cloud8 sessions, meetups, and skate events.
    </p>
  </section>
  <iframe
    [src]="iframeSrc"
    class="reveal-up reveal-up-delay-1 rounded-xl shadow-sm"
    style="border: solid 1px #777"
    width="100%"
    height="500"
    frameborder="0"
    scrolling="no"
  ></iframe>
</div>

// projects/nx-workspace/apps/ui/cloud-8-skate-react/src/app/components/features/calendar-section.tsx
import { useEffect, useState } from 'react';
import { useTranslation } from '../../i18n';

const CALENDAR_EMBED_URL = 'https://calendar.google.com/calendar/embed';
const CALENDAR_ID =
  'ZmU3OTU0MzJjMDlhYzNmMmE5ZDc4MDdkZGY1NjhkZGE3ZmZkY2I1YzNlZDdkZDA3OGNhNmE2OTNhNjVjNzdiN0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t';
const CALENDAR_TIMEZONE = 'America/Toronto';
const MOBILE_BREAKPOINT_PX = 768;
const CALENDAR_MODE = {
  AGENDA: 'AGENDA',
  MONTH: 'MONTH',
} as const;

const getModeForWidth = (width: number) =>
  width < MOBILE_BREAKPOINT_PX ? CALENDAR_MODE.AGENDA : CALENDAR_MODE.MONTH;

export function CalendarSection() {
  const { t } = useTranslation();
  const [mode, setMode] = useState(() => getModeForWidth(window.innerWidth));

  useEffect(() => {
    const onResize = () => setMode(getModeForWidth(window.innerWidth));
    window.addEventListener('resize', onResize);
    return () => window.removeEventListener('resize', onResize);
  }, []);

  const params = new URLSearchParams({
    wkst: '1',
    ctz: CALENDAR_TIMEZONE,
    title: t('CALENDAR.EMBED_TITLE'),
    src: CALENDAR_ID,
    mode,
  });

  return (
    <div className="lg:rounded-2xl lg:bg-white/70 lg:backdrop-blur-md lg:shadow-lg lg:p-10">
      <section className="mb-6 reveal-up hidden lg:block">
        <h2 className="mb-3 text-3xl font-bold lg:text-4xl">
          {t('CALENDAR.TITLE')}
        </h2>
        <p className="text-base leading-7 text-gray-700">
          {t('CALENDAR.DESCRIPTION')}
        </p>
      </section>
      <iframe
        src={`${CALENDAR_EMBED_URL}?${params}`}
        title={t('CALENDAR.EMBED_TITLE')}
        className="reveal-up reveal-up-delay-1 rounded-xl shadow-sm"
        style={{ border: 'solid 1px #777' }}
        width="100%"
        height="500"
        scrolling="no"
      />
    </div>
  );
}
