// projects/nx-workspace/apps/ui/personal-website-react/src/app/components/features/profile-card.tsx
export function ProfileCard() {
  return (
    <div className="text-center">
      <div className="flex justify-center mb-6">
        <img
          id="profile-picture"
          src="/assets/profile-picture.jpg"
          className="transition-transform duration-300 hover:scale-105 shadow-lg"
          alt="Harry Liu"
        />
      </div>
      <h1 className="text-3xl font-bold mb-2">Harry Liu</h1>
      <p className="text-gray-600 dark:text-gray-400">I code sometimes.</p>
    </div>
  );
}

// projects/nx-workspace/apps/ui/personal-website-frontend/src/app/components/features/profile-card/profile-card.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-profile-card',
  templateUrl: './profile-card.component.html',
  styles: [
    '#profile-picture {width: 120px; height: 120px; border-radius: 50%;}',
  ],
})
export class ProfileCardComponent {}

<div class="text-center">
  <div class="flex justify-center mb-6">
    <img
      id="profile-picture"
      src="assets/profile-picture.jpg"
      class="transition-transform duration-300 hover:scale-105 shadow-lg"
    />
  </div>
  <h1 class="text-3xl font-bold mb-2">Harry Liu</h1>
  <p class="text-gray-600 dark:text-gray-400">I code sometimes.</p>
</div>
