// projects/nx-workspace/apps/ui/personal-website-react/src/app/components/global/return-top-button.tsx
import { useEffect, useState } from 'react';

export function ReturnTopButton() {
  const [show, setShow] = useState(false);

  useEffect(() => {
    const onScroll = () => setShow(window.scrollY > 100);
    window.addEventListener('scroll', onScroll);
    return () => window.removeEventListener('scroll', onScroll);
  }, []);

  if (!show) return null;
  return (
    <button
      onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}
      className="fixed bottom-5 left-1/2 transform -translate-x-1/2 text-white rounded-full w-12 h-12 bg-gray-500 bg-opacity-20 hover:bg-opacity-100"
    >
      ^
    </button>
  );
}

// projects/nx-workspace/apps/ui/personal-website-frontend/src/app/components/global/return-top-button/return-top-button.component.ts
import { Component, HostListener } from '@angular/core';

@Component({
  standalone: true,
  selector: 'lib-return-top-button',
  templateUrl: './return-top-button.component.html',
})
export class ReturnTopButtonComponent {
  showScrollButton = false;

  @HostListener('window:scroll', [])
  onScroll() {
    this.showScrollButton = window.scrollY > 100;
  }

  scrollToTop(): void {
    window.scrollTo({ top: 0, behavior: 'smooth' });
  }
}

@if (showScrollButton) {
<button
  class="fixed bottom-5 left-1/2 transform -translate-x-1/2 text-white rounded-full w-12 h-12 bg-gray-500 bg-opacity-20 hover:bg-opacity-100"
  (click)="scrollToTop()"
>
  ^
</button>
}
