// projects/demo-apps/react-demo/src/pages/Todo/TodoList.tsx
import React, { useState } from 'react';
import { useTodos } from './TodoContext';

export default function TodoList() {
  const { todos, updateTodo, deleteTodo } = useTodos();
  const [editingId, setEditingId] = useState<number | null>(null);
  const [editingValue, setEditingValue] = useState('');

  const handleEditClick = (id: number, currentValue: string) => {
    setEditingId(id);
    setEditingValue(currentValue);
  };

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setEditingValue(e.target.value);
  };

  const handleTodoUpdate = () => {
    if (editingId !== null) {
      if (!editingValue) {
        deleteTodo(editingId);
        return;
      }
      updateTodo(editingId, editingValue);
      setEditingId(null);
      setEditingValue('');
    }
  };

  const handleInputKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Enter') {
      handleTodoUpdate();
    }
  };

  const handleDeleteClick = (id: number) => {
    deleteTodo(id);
  };

  return (
    <ul className="list-group">
      {todos.map(todo => (
        <li className="list-group-item" key={todo.id}>
          {editingId === todo.id ? (
            <input
              type="text"
              value={editingValue}
              onChange={handleInputChange}
              onBlur={handleTodoUpdate}
              onKeyDown={handleInputKeyDown}
              autoFocus
            />
          ) : (
            <span onClick={() => handleEditClick(todo.id, todo.title)}>
              {todo.title}
            </span>
          )}

          <div className="float-end">
            <button
              onClick={() => handleEditClick(todo.id, todo.title)}
              className="btn btn-primary me-2"
            >
              Edit
            </button>
            <button
              onClick={() => handleDeleteClick(todo.id)}
              className="btn btn-danger"
            >
              Delete
            </button>
          </div>
        </li>
      ))}
    </ul>
  );
}

// projects/demo-apps/vue-demo/src/components/TodoList.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useTodoStore } from '../store/todoStore'
import type { Todo } from '../store/todoStore'
import { storeToRefs } from 'pinia'

const todoStore = useTodoStore()
const { todos } = storeToRefs(todoStore)
const { fetchTodos, updateTodo, deleteTodo } = todoStore

const editingId = ref<number | null>(null)
const editingValue = ref<string | null>(null)

onMounted(async () => {
  await fetchTodos()
})

const handleEditClick = (todo: Todo) => {
  editingId.value = todo.id
  editingValue.value = todo.title
}

const handleTodoUpdate = () => {
  if (!editingValue.value) {
    deleteTodo(editingId.value!)
    return
  }
  updateTodo({ id: editingId.value!, title: editingValue.value })
  editingId.value = null
  editingValue.value = ''
}

</script>

<template>
    <ul class="list-group">
      <template v-if="todos.length">
        <li class="list-group-item" v-for="todo in todos" :key="todo.id">
          <input
            v-if="editingId === todo.id"
            type="text"
            v-model="editingValue"
            @blur="handleTodoUpdate"
            @keyup.enter="handleTodoUpdate"
          />
          <span v-else @click="handleEditClick(todo)">
            {{ todo.title }}
          </span>
          <div class="float-end">
            <button class="btn btn-primary me-2" @click="handleEditClick(todo)">Edit</button>
            <button class="btn btn-danger" @click="deleteTodo(todo.id)">Delete</button>
          </div>
        </li>
      </template>
      <p v-else class="text-center my-4">You currently have no todo items.</p>
    </ul>
</template>
