// projects/nx-workspace/apps/ui/cloud-8-skate-angular/src/app/components/pages/albums-page/albums-page.component.ts
import { Component } from '@angular/core';
import { ImageGalleryComponent } from '../../features/image-gallery/image-gallery.component';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import { ENVIRONMENT } from '../../../../environments/environment';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { INTERNAL_LINKS } from '../../../core/consts/routes.const';
import { ImageAlbum } from '@prettydamntired/personal-website-lib';

@Component({
  selector: 'app-albums-page',
  templateUrl: './albums-page.component.html',
  imports: [ImageGalleryComponent, CommonModule, RouterModule],
})
export class AlbumsPageComponent {
  albums!: ImageAlbum[];
  LINKS = INTERNAL_LINKS;
  constructor(private http: HttpClient) {
    this.getPosts().subscribe(res => (this.albums = res));
  }

  private getPosts(): Observable<any> {
    return this.http.get<any>(ENVIRONMENT.URLS.HEADLESS_CMS.IMAGE_ALBUMS);
  }
}

<app-content-container>
  <section class="mb-8 reveal-up">
    <h1 class="mb-4 text-3xl font-bold lg:text-4xl reveal-up reveal-up-delay-1">
      Gallery
    </h1>
    <p
      class="mb-8 text-base leading-7 text-gray-700 reveal-up reveal-up-delay-2"
    >
      Photos from Cloud8 sessions, meetups, and skate events.
    </p>

    @if (albums.length) {
    <div class="grid grid-cols-2 gap-6 lg:grid-cols-3">
      @for (album of albums; track trackAlbum($index, album)) {
      <a
        [routerLink]="[LINKS.ALBUMS.url.internal, album.slug]"
        class="block reveal-up"
      >
        @if (album.coverImageUrl) {
        <img
          [src]="album.coverImageUrl"
          [alt]="album.name"
          class="aspect-square w-full object-cover"
        />
        } @else {
        <div
          class="flex aspect-square items-center justify-center bg-gray-100 text-gray-500"
        >
          No cover image
        </div>
        }
        <p class="mt-2 text-center text-base font-semibold text-gray-900">
          {{ album.name }}
        </p>
        <p class="mt-1 text-center text-sm text-gray-500">
          {{ album.date | date : 'MMMM d, y' }}
        </p>
      </a>
      }
    </div>
    } @else if (!isLoading) {
    <div
      class="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm reveal-up"
    >
      <p class="text-base leading-7 text-gray-700">
        Gallery content is not available right now.
      </p>
    </div>
    }
  </section>
</app-content-container>

// projects/nx-workspace/apps/ui/cloud-8-skate-react/src/app/components/pages/albums.page.tsx
import { Link } from 'react-router-dom';
import { useTranslation } from '../../i18n';
import { ROUTE_PATH, albumPath } from '../../core/consts/routes.const';
import { formatAlbumDate } from '../../core/services/date.utils';
import { useSeo } from '../../core/services/seo';
import { getGalleryAlbums } from '../../core/services/sanity.service';
import { useAsyncData } from '../../core/services/use-async-data';
import { ContentContainer } from '../features/content-container';

export function AlbumsPage() {
  const { t } = useTranslation();
  const { data: albums, isLoading } = useAsyncData(getGalleryAlbums);
  useSeo({
    title: t('SEO.GALLERY.TITLE'),
    description: t('SEO.GALLERY.DESCRIPTION'),
    path: ROUTE_PATH.GALLERY,
    keywords: t('SEO.GALLERY.KEYWORDS'),
  });

  return (
    <ContentContainer>
      <section className="mb-8 reveal-up">
        {albums?.length ? (
          <div className="grid grid-cols-2 gap-6 lg:grid-cols-3">
            {albums.map(album => (
              <Link
                key={album._id}
                to={albumPath(album.slug)}
                className="block reveal-up"
              >
                {album.coverImageUrl ? (
                  <img
                    src={album.coverImageUrl}
                    alt={album.name}
                    className="aspect-square w-full object-cover"
                    loading="lazy"
                  />
                ) : (
                  <div className="flex aspect-square items-center justify-center bg-gray-100 text-gray-500">
                    {t('GALLERY.NO_COVER')}
                  </div>
                )}
                <p className="mt-2 text-center text-base font-semibold text-gray-900">
                  {album.name}
                </p>
                <p className="mt-1 text-center text-sm text-gray-500">
                  {formatAlbumDate(album.date)}
                </p>
              </Link>
            ))}
          </div>
        ) : (
          !isLoading && (
            <div className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm reveal-up">
              <p className="text-base leading-7 text-gray-700">
                {t('GALLERY.UNAVAILABLE')}
              </p>
            </div>
          )
        )}
      </section>
    </ContentContainer>
  );
}
