// projects/nx-workspace/apps/ui/cloud-8-skate-react/src/app/components/pages/contact.page.tsx
import { useTranslation } from '../../i18n';
import { ROUTE_PATH } from '../../core/consts/routes.const';
import { useSeo } from '../../core/services/seo';
import { ContactSection } from '../features/contact-section';
import { ContentContainer } from '../features/content-container';

export function ContactPage() {
  const { t } = useTranslation();
  useSeo({
    title: t('SEO.CONTACT.TITLE'),
    description: t('SEO.CONTACT.DESCRIPTION'),
    path: ROUTE_PATH.CONTACT,
    keywords: t('SEO.CONTACT.KEYWORDS'),
  });

  return (
    <ContentContainer>
      <div className="flex min-h-[calc(100dvh-10rem)]">
        <div className="w-full m-auto">
          <ContactSection />
        </div>
      </div>
    </ContentContainer>
  );
}

// projects/nx-workspace/apps/ui/cloud-8-skate-angular/src/app/components/pages/contact-page/contact-page.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { ContactSectionComponent } from '../../features/contact-section/contact-section.component';
import { ContentContainerComponent } from '../../features/content-container/content-container.component';
import { SeoService } from '../../../services/seo.service';

@Component({
  selector: 'app-contact-page',
  templateUrl: './contact-page.component.html',
  imports: [ContactSectionComponent, ContentContainerComponent],
})
export class ContactPageComponent implements OnInit {
  private seoService = inject(SeoService);

  ngOnInit() {
    this.seoService.updateMetaTags({
      title: 'Contact',
      description:
        'Get in touch with Cloud8Skate. Contact us for skating events, meetups, and general inquiries about our Toronto skating community.',
      url: 'https://cloud8skate.com/contact',
      keywords:
        'contact Cloud8, Toronto skating contact, skating meetup Toronto',
    });
  }
}

<app-content-container>
  <div class="flex min-h-[calc(100dvh-10rem)]">
    <div class="w-full m-auto">
      <app-contact-section></app-contact-section>
    </div>
  </div>
</app-content-container>
