// projects/nx-workspace/apps/ui/personal-website-frontend/src/app/components/features/toggle-dark-mode-button/toggle-dark-mode-button.component.ts
import { Component } from '@angular/core';
import { ThemeService } from 'general-components';

@Component({
  standalone: true,
  selector: 'app-toggle-dark-mode-button',
  templateUrl: './toggle-dark-mode-button.component.html',
})
export class ToggleDarkThemeButtonComponent {
  constructor(private themeService: ThemeService) {}
  toggleDarkMode(): void {
    this.themeService.toggleDarkMode();
  }
}

<button
  (click)="toggleDarkMode()"
  class="transition-all duration-200 hover:scale-110 hover:text-blue-600 dark:hover:text-blue-400"
>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="22"
    height="22"
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    stroke-width="2"
    stroke-linecap="round"
    stroke-linejoin="round"
  >
    <path d="M12 8a2.83 2.83 0 0 0 4 4 4 4 0 1 1-4-4" />
    <path d="M12 2v2" />
    <path d="M12 20v2" />
    <path d="m4.9 4.9 1.4 1.4" />
    <path d="m17.7 17.7 1.4 1.4" />
    <path d="M2 12h2" />
    <path d="M20 12h2" />
    <path d="m6.3 17.7-1.4 1.4" />
    <path d="m19.1 4.9-1.4 1.4" />
  </svg>
</button>

// projects/nx-workspace/apps/ui/personal-website-react/src/app/components/features/toggle-dark-mode-button.tsx
import { useTheme } from '../../core/services/theme-context';

export function ToggleDarkModeButton() {
  const { toggleDarkMode } = useTheme();
  return (
    <button
      onClick={toggleDarkMode}
      className="transition-all duration-200 hover:scale-110 hover:text-blue-600 dark:hover:text-blue-400"
      aria-label="Toggle dark mode"
    >
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="22"
        height="22"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      >
        <path d="M12 8a2.83 2.83 0 0 0 4 4 4 4 0 1 1-4-4" />
        <path d="M12 2v2" />
        <path d="M12 20v2" />
        <path d="m4.9 4.9 1.4 1.4" />
        <path d="m17.7 17.7 1.4 1.4" />
        <path d="M2 12h2" />
        <path d="M20 12h2" />
        <path d="m6.3 17.7-1.4 1.4" />
        <path d="m19.1 4.9-1.4 1.4" />
      </svg>
    </button>
  );
}
