// projects/nx-workspace/apps/ui/cloud-8-skate-react/src/app/components/pages/album.page.tsx
import { useParams } from 'react-router-dom';
import { useTranslation } from '../../i18n';
import { albumPath } from '../../core/consts/routes.const';
import { formatAlbumDate } from '../../core/services/date.utils';
import { useSeo } from '../../core/services/seo';
import { getGalleryAlbum } from '../../core/services/sanity.service';
import { useAsyncData } from '../../core/services/use-async-data';
import { ContentContainer } from '../features/content-container';
import { ImageGallery } from '../features/image-gallery';

export function AlbumPage() {
  const { t } = useTranslation();
  const { albumSlug = '' } = useParams();
  const { data: album, isLoading } = useAsyncData(
    () => getGalleryAlbum(albumSlug),
    albumSlug,
  );
  useSeo({
    title: album?.name ?? t('SEO.ALBUM.TITLE'),
    description:
      album?.description ||
      t('SEO.ALBUM.DESCRIPTION', { name: album?.name ?? '' }),
    path: albumPath(albumSlug),
    keywords: t('SEO.ALBUM.KEYWORDS'),
  });

  return (
    <ContentContainer>
      {album ? (
        <section className="mb-8">
          <h1 className="mb-4 text-3xl font-bold lg:text-4xl">{album.name}</h1>
          <p className="mb-2 text-sm text-gray-500">
            {formatAlbumDate(album.date)}
          </p>
          {album.description && (
            <p className="mb-8 text-base leading-7 text-gray-700">
              {album.description}
            </p>
          )}
          <ImageGallery images={album.images ?? []} />
        </section>
      ) : (
        !isLoading && (
          <section className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm">
            <p className="text-base leading-7 text-gray-700">
              {t('GALLERY.ALBUM_UNAVAILABLE')}
            </p>
          </section>
        )
      )}
    </ContentContainer>
  );
}

// projects/nx-workspace/apps/ui/cloud-8-skate-angular/src/app/components/pages/album-page/album-page.component.ts
import { Component, DestroyRef, inject, OnInit } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { ImageGalleryComponent } from '../../features/image-gallery/image-gallery.component';
import { of, switchMap } from 'rxjs';
import { ActivatedRoute } from '@angular/router';
import { CommonModule } from '@angular/common';
import {
  Cloud8GalleryAlbumDetail,
  Cloud8SanityService,
} from '../../../services/cloud8-sanity.service';
import { SeoService } from '../../../services/seo.service';

@Component({
  selector: 'app-album-page',
  templateUrl: './album-page.component.html',
  imports: [ImageGalleryComponent, CommonModule],
})
export class AlbumPageComponent implements OnInit {
  album: Cloud8GalleryAlbumDetail | null = null;
  isLoading = true;

  private route = inject(ActivatedRoute);
  private cloud8SanityService = inject(Cloud8SanityService);
  private seoService = inject(SeoService);
  private destroyRef = inject(DestroyRef);

  ngOnInit(): void {
    this.route.paramMap
      .pipe(
        switchMap(params => {
          const albumSlug = params.get('albumSlug');
          this.isLoading = true;

          if (!albumSlug) {
            return of(null);
          }

          return this.cloud8SanityService.getGalleryAlbum(albumSlug);
        }),
        takeUntilDestroyed(this.destroyRef),
      )
      .subscribe(album => {
        this.album = album;
        this.isLoading = false;

        if (!album) {
          return;
        }

        this.seoService.updateMetaTags({
          title: album.name,
          description:
            album.description ||
            `Cloud8Skate gallery album: ${album.name}. View photos from our Toronto skating sessions and events.`,
          url: `https://cloud8skate.com/gallery/${album.slug}`,
          keywords: 'Cloud8 gallery, Toronto skating photos, Cloud8 album',
        });
      });
  }
}

<app-content-container>
  @if (album; as currentAlbum) {
  <section class="mb-8">
    <h1 class="mb-4 text-3xl font-bold lg:text-4xl">
      {{ currentAlbum.name }}
    </h1>
    <p class="mb-2 text-sm text-gray-500">
      {{ currentAlbum.date | date : 'MMMM d, y' }}
    </p>
    @if (currentAlbum.description) {
    <p class="mb-8 text-base leading-7 text-gray-700">
      {{ currentAlbum.description }}
    </p>
    }
    <app-image-gallery [images]="currentAlbum.images"></app-image-gallery>
  </section>
  } @else if (!isLoading) {
  <section class="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm">
    <p class="text-base leading-7 text-gray-700">
      Gallery album content is not available right now.
    </p>
  </section>
  }
</app-content-container>
